"use client";
import {useEffect,useState,useRef} from 'react';
const seasons=[
{cn:'春',en:'SPRING',word:'萌生',title:'让日常，从一份水润开始。',text:'春雨润湿土壤，溪流绕过覆着新苔的石头，嫩芽舒展。细密泡泡轻轻铺开，把护肤的第一步变得柔软而简单。',color:'#c5d5a9'},
{cn:'夏',en:'SUMMER',word:'流动',title:'轻一点，留给肌肤更多自在。',text:'阳光穿过树叶，清透水流绕过暖石与湿润土壤。轻盈乳的设计从清爽肤感出发，追求易推开、柔润、不黏腻。',color:'#b2dbe2'},
{cn:'秋',en:'AUTUMN',word:'归土',title:'滋养，是每天温柔的积累。',text:'落叶回到湿润土壤，溪流穿过褐色石面。大米发酵灵感与淡淡米香，让日常滋养多一份温柔。',color:'#e4b992'},
{cn:'冬',en:'WINTER',word:'蕴藏',title:'四季改变，日常滋养始终相伴。',text:'霜覆石面，土壤休眠，溪流边缘结冰，生命静静积蓄。同一套水乳陪伴全年，根据肌肤感受调整用量，把滋养带进每一天。',color:'#e5e9ec'}];
export default function ProductExperience(){
const stageRef=useRef<HTMLElement>(null);
const [season,setSeason]=useState(0),[playing,setPlaying]=useState(true),[step,setStep]=useState(0),[beat,setBeat]=useState(0);
useEffect(()=>{if(!playing)return;const id=setInterval(()=>setSeason(v=>(v+1)%4),11000);return()=>clearInterval(id)},[playing]);
useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setBeat(Number((e.target as HTMLElement).dataset.beat))}),{threshold:.55});document.querySelectorAll('.storyBeat').forEach(el=>io.observe(el));return()=>io.disconnect()},[]);
const s=seasons[season];return <div className="productArea"><div className="productWindowBar"><span>SEASON_SOIL.EXE / 原创产品设计</span><span>— □ ×</span></div><section id="product" className="intro section"><div className="meta"><span>01 / ORIGINAL PRODUCT CONCEPT</span><span>SKINCARE · FOUR SEASONS</span></div><div className="introGrid"><div><p className="eyebrow">SEASON SOIL</p><h2>四时饮<em>Daily nourishment.</em></h2></div><div><h3>像每天喝水一样，<br/>自然地照顾肌肤。</h3><p>以四季与土壤的滋养循环为灵感，将泡泡水膜与轻盈屏障乳组合成一套便携的日常护肤构想。水润、轻盈，为后续上妆做好准备。</p><span className="tag">原创概念设计 / 尚未量产</span></div></div></section>
<section className={`seasonStage season-${season} ${playing?"":"motionPaused"}`} style={{'--accent':s.color} as React.CSSProperties} ref={stageRef} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--pointer-x",`${(e.clientX-r.left)/r.width-.5}`);e.currentTarget.style.setProperty("--pointer-y",`${(e.clientY-r.top)/r.height-.5}`)}} aria-label="四季自然动画"><div className="sceneryWrap" aria-hidden="true">{seasons.map((_,i)=><div key={i} className={`scenery scene${i} ${season===i?'active':''}`}><img className="seasonProductPhoto" src={`/photos/immersive-season-${i}.webp`} alt=""/></div>)}</div><div className="weatherLayers" aria-hidden="true"><div className="sunlight"/><div className="rain">{Array.from({length:36},(_,i)=><i key={i} style={{left:`${(i*29)%100}%`,animationDelay:`${i*-.29}s`,animationDuration:`${1.1+(i%5)*.18}s`}}/>)}</div><div className="productRaindrops">{Array.from({length:7},(_,i)=><i key={i} style={{left:`${64+i*2.4}%`,top:`${35+(i*13)%28}%`,animationDelay:`${i*-.7}s`}}/>)}</div><div className="leaves">{Array.from({length:12},(_,i)=><img src="/photos/falling-leaf.webp" key={i} alt="" style={{left:`${(i*23)%100}%`,width:`${22+(i%4)*9}px`,animationDelay:`${i*-1.7}s`,animationDuration:`${9+(i%4)*2}s`}}/>)}</div><div className="snow">{Array.from({length:65},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,width:`${2+i%5}px`,height:`${2+i%5}px`,animationDelay:`${i*-.8}s`,animationDuration:`${9+(i%7)*1.4}s`}}/>)}</div><div className="waterShimmer"/></div><div className="shade"/><div className="stageTop"><span>A YEAR IN NATURE</span><button onClick={()=>setPlaying(!playing)}>{playing?'Ⅱ 暂停动画':'▷ 播放动画'}</button></div><div className="stageCopy" key={season}><p className="eyebrow">{s.en} / {s.word}</p><h2>{s.cn}<small>{s.word}</small></h2><h3>{s.title}</h3><p className="sceneDescription">{s.text}</p></div><div className="stageBottom"><div className="seasonChoices" aria-label="选择季节">{seasons.map((x,i)=><button key={i} aria-pressed={season===i} onClick={()=>{setSeason(i);setPlaying(true)}}><span>0{i+1}</span>{x.cn}<small>{x.en}</small></button>)}</div><p>四季流转<br/><span>同一份日常滋养</span></p></div><div className="progress" key={`${season}-${playing}`}><i className={playing?'running':''}/></div></section>
<section className="scrollStory" aria-label="产品动画步骤">{[{t:'水滴 · 唤醒',p:'水落入土壤，让日常护理从滋养开始。',c:'drop'},{t:'泡泡 · 铺开',p:'细密泡泡水膜，探索水润而简单的第一步。',c:'bubbles'},{t:'米乳 · 成膜',p:'带着淡淡米香，由乳状延展为轻薄膜感。以不黏腻与屏障修护为设计目标。',c:'lotion'},{t:'日常 · 妆前',p:'两步护肤，为后续防晒与上妆做好准备。',c:'ready'}].map((x,i)=><article key={x.c} className={`storyBeat ${x.c} ${beat===i?'inView':''}`} data-beat={i}><div className="storyVisual" aria-hidden="true">{i===0?<i className="waterDrop"/>:i===1?<img className="storyTexture" src="/photos/real-foam.webp" alt="细密真实泡泡质地概念近景"/>:i===2?<img className="storyTexture" src="/photos/rice-film.webp" alt="乳液铺展为透明薄膜的质地概念近景"/>:<div className="readyRing"><span>01 + 02</span></div>}</div><div><span>0{i+1} / DAILY RITUAL</span><h3>{x.t}</h3><p>{x.p}</p></div></article>)}</section><section className="duo section"><div className="meta"><span>02 / THE DAILY DUO</span><span>一份水润 · 一份轻盈</span></div><h2>两步，回到简单。</h2><div className="duoGrid"><article className="foamCard"><div className="realTexture"><img src="/photos/real-foam.webp" alt="水膜的绵密湿润泡泡，真实质感概念图" loading="lazy"/><span>MICRO-FOAM / 细密泡泡</span></div><div className="cardCopy"><span>STEP 01 / WATER</span><h3>泡泡水膜</h3><p>从细密泡泡，到水润薄膜。<br/>以免洗日常护理为探索方向，让第一步轻松融入生活。</p><div className="tags"><span>细密</span><span>水润</span><span>易铺开</span></div></div></article><article className="milkCard"><div className="realTexture"><img src="/photos/rice-film.webp" alt="米香乳从乳状到薄膜的真实质感概念图" loading="lazy"/><span>LOTION TO FILM / 乳化成膜</span></div><div className="cardCopy"><span>STEP 02 / LOTION</span><h3>米香轻盈屏障乳</h3><p>拟加入大米发酵来源成分，保留淡淡米香。<br/>从柔润乳状铺展为轻薄膜感，以清爽不黏、四季适用与屏障修护为研发目标。</p><div className="tags"><span>米香</span><span>轻薄膜感</span><span>四季</span></div></div></article></div><p className="smallNote">图片为真实质感的生成概念图，并非实物拍摄。大米发酵原料、米香来源、成膜表现与功效待配方研发及测试确认。</p></section>
<section className="ritual section"><div><p className="eyebrow">FROM SKINCARE TO MAKEUP</p><h2>留给底妆，<br/><em>一个舒服的开始。</em></h2><p>不卡粉、不黏腻，是这套产品希望实现的体验。<br/>从日常护理，到妆前准备，每一步都尽量简单。</p></div><div className="steps">{[{t:'水膜铺开',en:'HYDRATE',p:'取适量泡泡水膜，轻柔铺开。使用方式与等待时间以最终配方为准。'},{t:'轻乳收尾',en:'NOURISH',p:'以轻盈乳完成护理，根据肤感调整用量，等待表面舒适后继续下一步。'},{t:'进入日常',en:'GET READY',p:'白天继续防晒与上妆。与不同防晒、粉底搭配的搓泥及浮粉表现列入测试。'}].map((x,i)=><button key={i} className={step===i?'selected':''} aria-expanded={step===i} onClick={()=>setStep(i)}><span>0{i+1}</span><div><small>{x.en}</small><h3>{x.t}</h3>{step===i&&<p>{x.p}</p>}</div><b>{step===i?'−':'+'}</b></button>)}</div></section>
<section className="design section"><div className="meta"><span>03 / BEHIND THE DESIGN</span><span>从需求到验证</span></div><h2>好看的背后，<br/>每个选择都有理由。</h2><div className="designGrid">{[{t:'理解日常',p:'聚焦通勤、出差与短途旅行，减少分装的麻烦，让两步护肤方便携带。'},{t:'组合携带',p:'探索可组合、可拆分的双容器结构。水膜与乳液分别出液，结构围绕起泡机制开发。'},{t:'四季共用',p:'同一套产品贯穿全年，以自然场景表达季节变化，根据肤感调整用量。'},{t:'体验验证',p:'后续验证防漏、出液、黏腻感、屏障修护表现与底妆兼容性。'}].map((x,i)=><article key={i}><span>0{i+1}</span><h3>{x.t}</h3><p>{x.p}</p></article>)}</div></section>
</div>}